apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-06T21:36:38Z"
  labels:
    app: sussex-demo
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2020-12-06T21:36:38Z"
  name: sussex-demo
  namespace: default
  resourceVersion: "11041"
  selfLink: /api/v1/namespaces/default/services/sussex-demo
  uid: 1aee58a4-d043-43db-9191-b749aeb756eb
spec:
  clusterIP: 10.97.131.254
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31801
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sussex-demo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
