spring.jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
      format_sql: true
      jdbc.lob.non_contextual_creation: true
      ddl-auto: create-drop

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  password: mysecretpassword
  username: postgres
  driver-class-name: org.postgresql.Driver

clients:
  google:
    base-url: http://localhost:8080

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - com.georgeracu.demo.springboot.port.out.client.RetryableException
  instances:
    backendA:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.georgeracu.demo.springboot.port.out.client.RetryableException
  instances:
    backendA:
      baseConfig: default
