version: '3.1'

volumes:
  postgres_data:
    driver: local

services:
  hotel-db:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - "5432:5432"
